[package]
name = "myshell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
thiserror = "1.0.31"
nix = "0.24.2"
whoami = "1.2.1"
